% ELFE - programmation logique et fonctionelle, evidemment!
% Licence 3 informatique, universite Lille 1
% auteurs: C. Bouillaguet et C. Kuttler
% les princesses et les tigres (1/4)

contenu(tigre).
contenu(princesse).

affiche_1(princesse,princesse):-contenu(princesse),contenu(princesse).
affiche_2(princesse,princesse):-contenu(princesse),contenu(princesse).

porte_1(X,Y) :- affiche_1(X,Y),X=princesse.
porte_2(X,Y) :- affiche_2(X,Y),X=tigre.
